// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-jBT30gGw4T0fyOjROpVxjlSaugTH4E',
    appId: '1:236563075553:web:48ab80e2478dbe602102a0',
    messagingSenderId: '236563075553',
    projectId: 'herflowmate-bf7e1',
    authDomain: 'herflowmate-bf7e1.firebaseapp.com',
    storageBucket: 'herflowmate-bf7e1.firebasestorage.app',
    measurementId: 'G-RZ2FCX6K6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpc2jM2AGOwrD2dUNVlltKf0ZLTTpNrYU',
    appId: '1:236563075553:android:6391eda6a50715982102a0',
    messagingSenderId: '236563075553',
    projectId: 'herflowmate-bf7e1',
    storageBucket: 'herflowmate-bf7e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92p6g6SUZFH-bptlJEwC4sSPEWb7t5R8',
    appId: '1:236563075553:ios:d6406526e971b1f62102a0',
    messagingSenderId: '236563075553',
    projectId: 'herflowmate-bf7e1',
    storageBucket: 'herflowmate-bf7e1.firebasestorage.app',
    iosBundleId: 'com.herflowmate.herFlowmate',
  );

}